<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-10-24 11:42
=======
# Generated by Django 4.1 on 2022-10-24 13:44
>>>>>>> 3cedef29d8c012cf98ffdac0c7bdc9d25e6e7677

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
    ]
