# Generated by Django 3.2.16 on 2022-10-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_home', '0002_cedric'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cedric',
            new_name='Ingredients',
        ),
    ]
