# Generated by Django 4.1.2 on 2022-10-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_home', '0003_students_delete_apimodel_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='section',
            field=models.CharField(max_length=100),
        ),
    ]
