# Generated by Django 4.1.2 on 2022-10-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_home', '0005_remove_students_email_remove_students_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='students',
            name='section',
            field=models.CharField(max_length=800),
        ),
    ]
