# Generated by Django 4.1.2 on 2022-10-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_home', '0006_alter_students_name_alter_students_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='students',
            name='section',
            field=models.TextField(max_length=800),
        ),
    ]
