# Generated by Django 4.1.2 on 2022-10-26 07:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_home', '0007_alter_students_name_alter_students_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteins', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Boeuf'), (2, 'Veau'), (3, 'Saumon'), (4, 'Oeufs')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='students',
            name='section',
            field=models.TextField(max_length=300),
        ),
    ]
