# Generated by Django 4.1.2 on 2022-10-26 09:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_home', '0008_ingred_alter_students_name_alter_students_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingred',
            name='veggies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Haricots Verts'), (2, 'Brocoli'), (3, 'Poivron'), (4, 'Tomate')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='ingred',
            name='proteins',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Boeuf'), (2, 'Veau'), (3, 'Saumon'), (4, 'Oeufs')], max_length=10, null=True),
        ),
    ]
