# Generated by Django 4.1.2 on 2022-10-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_home', '0009_ingred_veggies_alter_ingred_proteins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingred',
            new_name='IngredientsModel',
        ),
    ]
