# Generated by Django 4.1.2 on 2022-10-26 14:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_home', '0010_rename_ingred_ingredientsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsmodel',
            name='proteins',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Boeuf'), (2, 'Veau'), (3, 'Saumon'), (4, 'Oeufs')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientsmodel',
            name='veggies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Haricots Verts'), (2, 'Brocoli'), (3, 'Poivron'), (4, 'Tomate')], max_length=100, null=True),
        ),
    ]
