# Generated by Django 4.1 on 2022-10-27 08:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_home', '0014_rename_veggies_ingredientsmodel_vegetables_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsmodel',
            name='legumes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[[1, 'Chickpea'], [2, 'Kidney bean'], [3, 'Lentils'], [4, 'Navy bean']], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientsmodel',
            name='spices_and_herbs',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[[1, 'Curcuma'], [2, 'Curry paste'], [3, 'Oregano'], [4, 'Thyme']], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientsmodel',
            name='starch',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[[1, 'Bread'], [2, 'Pasta'], [3, 'Potato'], [4, 'Rice'], [5, 'Semolina'], [6, 'Wheat'], [7, 'Wheat flour']], max_length=500, null=True),
        ),
    ]
