# Generated by Django 4.1 on 2022-10-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cedric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
