# Generated by Django 4.1.2 on 2022-10-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_home', '0003_rename_cedric_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='ingredients',
            name='ingredients',
            field=models.ManyToManyField(to='api_home.ingredient'),
        ),
    ]
