# Generated by Django 4.1.2 on 2022-10-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_home', '0004_ingredient_ingredients_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizontal_choices', models.SmallIntegerField(choices=[('Beef', 'Boeuf'), ('Veal', 'Veau'), ('Salmon', 'Saumon'), ('Eggs', 'Oeufs')], default=1, help_text='Horizontal choices look like this')),
                ('vertical_choices', models.SmallIntegerField(choices=[('Grean Beans', 'Haricots Verts'), ('Broccoli', 'Brocoli'), ('Bell Pepper', 'Poivron'), ('Tomato', 'Tomate')], default=2, help_text='Some help on vertical choices')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
