# Generated by Django 4.1.2 on 2022-10-26 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_home', '0007_alter_mymodel_my_field2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='my_field2',
            new_name='proteins',
        ),
    ]
