# Generated by Django 4.1.2 on 2022-10-26 05:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_home', '0008_rename_my_field2_mymodel_proteins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='proteins',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Boeuf'), (2, 'Veau'), (3, 'Saumon'), (4, 'Oeufs')], max_length=5),
        ),
    ]
