# Generated by Django 4.1 on 2022-10-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_home', '0011_mymodel_veggies_alter_mymodel_proteins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='IngredientsModel',
        ),
    ]
