# Generated by Django 4.1.2 on 2022-11-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_home', '0015_alter_ingredientsmodel_legumes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.CharField(max_length=500)),
            ],
        ),
    ]
