# Generated by Django 4.1.2 on 2022-11-03 00:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_home', '0016_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsmodel',
            name='proteins',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[[1, 'Beef'], [2, 'Chicken'], [3, 'Cod'], [4, 'Lamb'], [5, 'Monk fish'], [6, 'Pork'], [7, 'Shrimps'], [8, 'Tuna'], [9, 'Turkey'], [10, 'Veal']], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientsmodel',
            name='starch',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[[1, 'Bread'], [2, 'Pasta'], [3, 'Potato'], [4, 'Rice'], [5, 'Semolina'], [6, 'Wheat']], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientsmodel',
            name='vegetables',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[[1, 'Broccoli'], [2, 'Carrot'], [3, 'Eggplant'], [4, 'Fennel'], [5, 'Garlic'], [6, 'Green bean'], [7, 'Onion'], [8, 'Shallot'], [9, 'Spinach'], [10, 'Tomato']], max_length=500, null=True),
        ),
    ]
